---
title: "Sentiment analysis - Svevo corpus of italian letters"
output: html_document
---

# Sentiment Analysis
Sentiment analysis of italian letter in Svevo Corpus.

```{r load dataset, warning = FALSE}
# load functions for sentiment analysis
source("sentiment/sentiment_functions.R")
# Load dataset with lemmatized words
corpus_ita <- read.csv("csv/cleaned_svevo_dataset_ITA.csv", sep=",", encoding = "UTF-8")
library(tidyverse)
library(tidytext)
library(textdata)
document_words <- corpus_ita %>%
  unnest_tokens(word, tokens) %>%
  count(letter_number, word)
```

Summarise sentiments for all documents in our corpus:
```{r, warning = FALSE}
# assign positive-negative-neutral scores to all the documents
sentiment_docs <- get_sentiment(document_words, corpus_ita) #takes a little bit of time 
```


Analyze how sentiments evolved over time:

```{r plot sentiment trend over time}
#input: set of sentiments {positive, negative, neutral}
#output: their trend over time
library(dplyr)
library(ggplot2)
library(tidyr)

sentiment_labels <- c("neutral", "positive", "negative")

sentiment_time <- sentiment_docs %>%
  group_by(date) %>%
  summarise(across(sentiment_labels, sum))

sentiment_time <- sentiment_time  %>% mutate(n = negative/(negative+positive+neutral), p = positive/(negative+positive+neutral),
                                             ne = neutral/(negative+positive+neutral))
sentiment_time$negative <- sentiment_time$n
sentiment_time$positive <- sentiment_time$p
sentiment_time$neutral <- sentiment_time$ne
sentiment_time[, -((ncol(sentiment_time) - 2):ncol(sentiment_time))]

sentiment_time %>%
    ggplot() +
    geom_line(aes(x=date, y=neutral, colour="neutral", group = 1),ylab="")+
    geom_point(aes(x=date, y=neutral, colour="neutral", group = 1),ylab="") +
    geom_line(aes(x=date, y=negative, colour="negative", group = 1),ylab="")+
    geom_point(aes(x=date, y=negative, colour="negative", group = 1),ylab="")+
    geom_line(aes(x=date, y=positive, colour="positive", group = 1),ylab="")+
    geom_point(aes(x=date, y=positive, colour="positive", group = 1),ylab="") +
    scale_colour_manual(values = c("positive" = "#fcba03", "negative" = "#097aab", "neutral" = "black")) +
    labs( y = "") +
    theme(legend.title=element_blank(), 
    legend.text=element_text(size=9))

ggsave(paste0( "plots/sentiment_time.png"), width = 20, height = 12, dpi = 150)

```

```{r plot sentiment trend over people}
#input: set of sentiments {positive, negative, neutral}
#output: their trend over people
library(dplyr)
library(ggplot2)
library(tidyr)

sentiment_labels <- c("neutral", "positive", "negative")

sentiment_people <- sentiment_docs[,-1] %>%
  group_by(pair) %>%
  mutate(count = n()) %>%
  filter(count > 2) %>%
  group_by(pair, count) %>%
  summarise(across(sentiment_labels, sum)) 

sentiment_people <- sentiment_people  %>% mutate(n = 100*negative/(negative+positive+neutral),
                                                 p = 100*positive/(negative+positive+neutral),
                                                  ne = 100*neutral/(negative+positive+neutral))
sentiment_people$negative <- sentiment_people$n
sentiment_people$positive <- sentiment_people$p
sentiment_people$neutral <- sentiment_people$ne
sentiment_people <- sentiment_people[, -((ncol(sentiment_people) - 2):ncol(sentiment_people))]

data <- data.frame(
  group=LETTERS[1:5],
  value=c(13,7,9,21,2)
)


sentiment_people <- melt(sentiment_people, id = c("pair", "count")) 


sentiment_people %>%
  ggplot() + 
  geom_bar(aes(x = pair, y = value, fill = variable), position = "dodge", stat = "identity")


```


```{r plot sentiment trend over topics}
#input: one topic 
#output: a value for each sentiment in the set = {positive, negative, neutral}
library(dplyr)
library(ggplot2)
library(tidyr)

# get sentiments associated to each topic
sentiment_topic <- get_sentiment_topic() 
sentiment_topic <-  melt(sentiment_topic, id = c("topic")) %>% group_by(topic) 
sentiment_topic <- sentiment_topic[order(sentiment_topic$topic),]
  

sentiment_topic %>%
  ggplot() +
  geom_bar(aes(x = topic, y = value, fill = variable), position = "dodge", stat = "identity")


ggplot(data=sentiment_topic, aes(x=" ", y=value, group=variable, fill=variable)) +
         geom_bar(width = 1, stat = "identity") +
         coord_polar("y", start=0) + 
         facet_wrap(.~ topic, nrow=2) + 
         scale_fill_brewer(palette="Greens")+
         theme_void()+
         theme(legend.position = c(0.85, 0.27))+
         theme(legend.title=element_blank(),
         legend.text=element_text(size=50))+
         theme(strip.text=element_text(size=50,face="bold"))

ggsave(paste0( "plots/topics_sentiment.png"), width = 25, height = 12, dpi = 500)


```

```{r plot emotions trend over time}
dfEmotion <- read.csv("csv/sentiment_year.csv", sep = ";") 
dfEmotionTime <- dfEmotion
dfEmotionTime <- get_emotions_time(dfEmotionTime)
ggplot() + 
  geom_line(data = dfEmotionTime, aes(x = year, y = sadness, colour = "Sadness"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = joy, colour = "Joy"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = fear, colour = "Fear"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = anger, colour = "Anger"), group = 1) +
  labs(color = "Emotions")
  
```



```{r plot emotions trend over time}

dfEmotion <- read.csv("csv/sentiment_year.csv", sep = ";", encoding = "UTF-8") 
dfEmotion
dfEmotionTime <- dfEmotion
dfEmotionTime <- get_emotions_time(dfEmotionTime)
ggplot() + 
  geom_line(data = dfEmotionTime, aes(x = year, y = sadness, colour = "Sadness"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = joy, colour = "Joy"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = fear, colour = "Fear"), group = 1) +
  geom_line(data = dfEmotionTime, aes(x = year, y = anger, colour = "Anger"), group = 1) +
  labs(color = "Emotions")
  
ggsave("plots/emotionOnTime.png", width=16, height=9, dpi=200)
```

```{r}
dfEmotionPair <- read.csv("csv/sentiment_pair.csv", sep = ";", encoding = "UTF-8")
dfEmotionPair <- get_emotions_pair(dfEmotionPair)
  
dfEmotionPairTmp <- dfEmotionPair
dfEmotionPairTmp$countPair <- NULL
dfEmotionPairTmp$positive <- NULL
dfEmotionPairTmp$negative <- NULL
emotion_people <- melt(dfEmotionPairTmp, id = c("pair"))
emotion_people$Emotions <- emotion_people$variable
emotion_people$variable <- NULL
emotion_people$Person <- emotion_people$pair
emotion_people$pair <- NULL
emotion_people %>%
  ggplot() +
  geom_bar(aes(x = Person, y = value, fill = Emotions), position = "fill", stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(variable = "Emotions")
ggsave("plots/emotionOnPeople.png", width=16, height=9, dpi=200)
```
